/* ---------- i18n ---------- */
const I18N={
 ru:{name:'Русский',docTitle:'Грибочек',title:'Грибочек',
  intro:'Четыре уровня, каждый раз новые: болотный лес с крокодилом, пустыня с драконом, высокое болото с гидрой и ледяная пещера со снеговиком. На каждом уровне спрятано не больше двух хорошо замаскированных тайников.',
  play:'Играть',settings:'Настройки',settingsHint:'Настройки (Esc)',resume:'Продолжить',back:'Назад',restart:'Заново этот уровень',newMap:'Новая карта',
  language:'Язык',controls:'Управление',sporesGotL:n=>`Собрано спор: ${n}`,time:t=>`Время: ${t}`,seedL:s=>`Карта №${s}`,
  winTitle:'Победа!',winText:'Злой снеговик растаял, и в пещере наступила тишина. Грибочек прошла все четыре уровня и может возвращаться домой.',again:'Сыграть ещё',rotate:'Поверни телефон горизонтально.',
  nextTitle:'Уровень 2: пустыня',nextText:'Дверь пенька ведёт в пески, к руинам древнего восточного города. Здесь живут скорпионы, попугаи-хулиганы, песчаные черви, кактусы-стрелки, мумии и жуки-скарабеи, а в конце ждёт огненный дракон.',nextTip:'Берегись зыбучих песков: в них нельзя стоять, выбирайся короткими прыжками. Дракон уязвим для удара рукой, когда устаёт после пикирования и опускает голову. Голова получает на 40% больше урона. Когда земля вспыхивает — прыгай на платформу.',next:'Дальше',next3Title:'Уровень 3: болото',next3Text:'За дверью — топкое болото, и чем дальше, тем выше деревья. Здесь хозяйничают люди-ящеры: мечники, маги и закованный в броню командир, а на длинных ветвях стоят их хижины. В кустах сидят гоблины в тотемных масках, по веткам скачут жабы-языкачи, под ветками ждут пауки, над водой вьются комары, в широких заводях плавают пираньи, а в ядовитой заводи живёт трёхголовая гидра.',next3Tip:'Горящие глаза в кустах — там засел гоблин с духовой трубкой; удар по кусту выгонит его. Бочки и ящики разбиваются ударом или рывком. Хижина ящеров выпускает воинов, пока её не сломаешь. Комар перед броском показывает красный пунктир — отойди с линии, а промахнувшись, он застревает. Плоты и лифты на лианах возят над болотом. Трухлявые ветки обваливаются, если на них постоять, но упасть в болото не страшно: доплыви до ближайшего дерева и залезь обратно. Командира не пробить, пока не собьёшь с него шлем прыжком, — потом бей по голове. После двух прыжков по голове он прикрывает её рукой: на руке можно стоять, но прыгать по голове бесполезно — бей рукой. Прыжок по голове гидры ранит её, но после трёх прыжков подряд голова звереет — у неё загораются глаза. Отруби все три головы — они отрастут, а яд в заводи поднимется. Зелёный пунктир — это прицел лазера: уходи с линии.',
  levelName:n=>T('lvlName'+n),lvlName1:'Уровень 1: лес',lvlName2:'Уровень 2: пустыня',lvlName3:'Уровень 3: болото',
  keys:[['← →','бег (A, D)'],['Пробел','прыжок, держи для высоты; с зонтиком — парение; в воде — гребок (W, ↑)'],['K','удар рукой с ударной волной (X); удары по врагам восполняют ману'],['L','бросок гриба, тратит ману (C)'],['Левый Shift','рывок, в воздухе тоже'],['↓ + прыжок','спрыгнуть с доски'],['E или ↓','лавка у продавца'],['Прыжок на врага','держи прыжок — высокий отскок от головы'],['Esc','настройки и пауза (P)']],
  touchKeys:[['◀ ▶','бег'],['прыг','прыжок; в воде — гребок'],['удар','удар рукой с ударной волной'],['гриб','бросок гриба, тратит ману'],['рывок','рывок, в воздухе тоже'],['лавка','появляется рядом с продавцом'],['❚❚','настройки и пауза']],
  tJump:'прыг',tShoot:'удар',tThrow:'гриб',fNoMana:'мало маны',manaL:'маны',boughtL:'куплено',tDash:'рывок',tShop:'лавка',
  boss:'Болотный крокодил',boss2:'Огненный дракон',boss3:'Болотная гидра',fHelm:'шлем слетел!',fGuard:'прикрыл голову!',fRage:'голова в ярости!',fPhase2h:'гидра в ярости!',fTide:'яд поднимается!',fStage:n=>`стадия ${n}: головы отросли!`,fPowerLost:'сила пропала',fSaved:'сохранено',fDoor:'дверь открыта',fHeartFull:'+2 споры',
  fPower1:'бросок гриба!',fPower2:'двойной гриб!',fPower3:'тройной гриб!',fPowerMax:'сила на максимуме',fSecret:'тайник!',secretsL:(a,b)=>`Тайники: ${a} из ${b}`,fPhase2:'дракон в ярости!',fPhase2c:'крокодил в ярости!',musicL:'Музыка',on:'вкл',off:'выкл',sound:'Звук',musicVol:'Громкость музыки',sfxVol:'Громкость эффектов',pressKey:'Enter, Пробел или K — продолжить',chooseLevel:'Выбор уровня',quit:'Выйти',menuHint:'Стрелки — выбор, Enter — подтвердить, Esc — назад',lvl1Desc:'Болотный лес · босс: крокодил',lvl2Desc:'Пустыня · босс: огненный дракон',lvl3Desc:'Высокое болото · босс: гидра',bossRow:'Сразу к боссу',bossRowDesc:'6 сердец, 200 спор, старт у последней лавки перед боссом.',bossShort:n=>T('bossShort'+n),bossShort1:'Крокодил',bossShort2:'Дракон',bossShort3:'Гидра',byeTitle:'Спасибо за игру!',byeText:'Браузер не разрешает странице закрыть вкладку самой. Просто закройте её, когда захотите.',toMenu:'В главное меню',mainMenu:'Главное меню',shopSign:'ЛАВКА',
  shopTitle:'Лавка крота-старьёвщика',sellerLine:'«Всё своё ношу с собой! Споры беру, сдачу не даю.»',wallet:n=>`Твои споры: ${n}`,leave:'Уйти',thanks:'«Приятно иметь дело.»',
  shopHint:'Стрелки — выбор, Enter или K — купить, 1–7 — быстро купить, Esc — уйти',
  healName:'Лечебный отвар',healDesc:'восстанавливает 1 сердце',maxhpName:'Сердце-жёлудь',maxhpDesc:'+1 к максимуму сердец (до 7), с каждым дороже на 5',heartsSold:(a,b)=>`Продано: ${a} из ${b}`,
  cloakName:'Плащ',cloakDesc:'второй рывок в воздухе',umbrellaName:'Зонтик',umbrellaDesc:'держи прыжок в падении — плавно паришь',
  mushName:'Красный гриб',mushDesc:'+100 маны',manaUpName:'Звёздная пыльца',manaUpDesc:'увеличивает запас маны на 25% (до 4 раз)',shotsName:'Грибная связка',shotsDesc:'по 2 гриба за бросок (8 маны), потом по 3 (10)',
  noMoney:'не хватает спор',fullHp:'здоровье и так полное',maxHp:'больше сердец не унести',fullMana:'мана и так полная',owned:'уже куплено',
  shopPrompt:'E — лавка',buyLabel:(n,p)=>`Купить «${n}» за ${p} спор`},
 en:{name:'English',docTitle:'Mushroom Girl',title:'Mushroom Girl',
  intro:'Four levels, freshly generated every run: a swamp forest with a crocodile, a desert with a dragon, a tall swamp with a hydra and an ice cave with a snowman. Every level hides up to two well-disguised secrets.',
  play:'Play',settings:'Settings',settingsHint:'Settings (Esc)',resume:'Resume',back:'Back',restart:'Restart this level',newMap:'New map',
  language:'Language',controls:'Controls',sporesGotL:n=>`Spores collected: ${n}`,time:t=>`Time: ${t}`,seedL:s=>`Map #${s}`,
  winTitle:'Victory!',winText:'The grumpy snowman has melted and the cave is quiet at last. Mushroom Girl has made it through all four levels and can head home.',again:'Play again',rotate:'Turn your phone sideways.',
  nextTitle:'Level 2: Desert',nextText:'The stump door leads into the sands and the ruins of an old eastern city. Scorpions, rowdy parrots, sandworms, cactus shooters, mummies and scarab beetles live here, and a fire dragon waits at the end.',nextTip:'Watch out for quicksand: don’t stand still in it, hop your way out. The dragon is open to punches when it gets tired after a dive and lowers its head. The head takes 40% more damage. When the ground ignites, jump onto a platform.',next:'Continue',next3Title:'Level 3: Swamp',next3Text:'Beyond the door lies a deep swamp, and the further you go, the taller the trees. Lizardmen rule here: swordsmen, mages and an armoured commander, with huts on the long boughs. Goblins in totem masks hide in the bushes, tongue toads hop along the branches, spiders wait under them, mosquitoes hover over the water, piranhas swim in the wide pools, and a three-headed hydra lurks in the poisoned pool.',next3Tip:'Burning eyes in a bush mean a goblin with a blowgun; hit the bush to flush him out. Barrels and crates break with a punch or a dash. A lizardman hut keeps sending out warriors until you wreck it. A mosquito shows a red dashed line before it dives: step aside, and if it misses it gets stuck. Rafts and vine lifts carry you over the bog. Rotten branches give way if you stand on them, but falling into the bog is fine: swim to the nearest tree and climb back up. The commander can’t be hurt until you stomp his helmet off; then aim for his head. After two stomps he covers his head with an arm: you can stand on it, but stomps won’t work, so punch. Stomping a hydra head hurts it, but three quick stomps drive it berserk: watch for burning eyes. Take down all three heads and they grow back while the poison rises. A dashed green outline is the laser’s aim: get out of the line.',
  levelName:n=>T('lvlName'+n),lvlName1:'Level 1: Forest',lvlName2:'Level 2: Desert',lvlName3:'Level 3: Swamp',
  keys:[['← →','run (A, D)'],['Space','jump, hold to go higher; glide with the umbrella; swim stroke in water (W, ↑)'],['K','punch with a shockwave (X); hits on foes restore mana'],['L','throw a mushroom, costs mana (C)'],['Left Shift','dash, works in the air too'],['↓ + jump','drop through a plank'],['E or ↓','shop at the merchant'],['Jump on a foe','hold jump for a high bounce off its head'],['Esc','settings and pause (P)']],
  touchKeys:[['◀ ▶','run'],['jump','jump; swim stroke in water'],['attack','punch with a shockwave'],['shroom','throw a mushroom, costs mana'],['dash','dash, works in the air too'],['shop','appears next to the merchant'],['❚❚','settings and pause']],
  tJump:'jump',tShoot:'attack',tThrow:'shroom',fNoMana:'not enough mana',manaL:'mana',boughtL:'bought',tDash:'dash',tShop:'shop',
  boss:'Swamp Crocodile',boss2:'Fire Dragon',boss3:'Swamp Hydra',fHelm:'helmet off!',fGuard:'head covered!',fRage:'the head is furious!',fPhase2h:'the hydra is enraged!',fTide:'the poison is rising!',fStage:n=>`stage ${n}: the heads grow back!`,fPowerLost:'power lost',fSaved:'saved',fDoor:'the door is open',fHeartFull:'+2 spores',
  fPower1:'mushroom throw!',fPower2:'double mushroom!',fPower3:'triple mushroom!',fPowerMax:'power maxed out',fSecret:'secret stash!',secretsL:(a,b)=>`Secrets: ${a} of ${b}`,fPhase2:'the dragon is enraged!',fPhase2c:'the crocodile is enraged!',musicL:'Music',on:'on',off:'off',sound:'Sound',musicVol:'Music volume',sfxVol:'Effects volume',pressKey:'Enter, Space or K to continue',chooseLevel:'Choose level',quit:'Quit',menuHint:'Arrows to select, Enter to confirm, Esc to go back',lvl1Desc:'Swamp forest · boss: crocodile',lvl2Desc:'Desert · boss: fire dragon',lvl3Desc:'Tall swamp · boss: hydra',bossRow:'Straight to the boss',bossRowDesc:'6 hearts, 200 spores, start at the last shop before the boss.',bossShort:n=>T('bossShort'+n),bossShort1:'Crocodile',bossShort2:'Dragon',bossShort3:'Hydra',byeTitle:'Thanks for playing!',byeText:'Browsers don’t let a page close its own tab. Just close it whenever you like.',toMenu:'Main menu',mainMenu:'Main menu',shopSign:'SHOP',
  shopTitle:'The Old Mole’s Stall',sellerLine:'“I carry my whole shop on my back! Spores only, no change.”',wallet:n=>`Your spores: ${n}`,leave:'Leave',thanks:'“A pleasure doing business.”',
  shopHint:'Arrows to select, Enter or K to buy, 1–7 quick buy, Esc to leave',
  healName:'Healing brew',healDesc:'restores 1 heart',maxhpName:'Acorn heart',maxhpDesc:'+1 max heart (up to 7), each costs 5 more',heartsSold:(a,b)=>`Sold: ${a} of ${b}`,
  cloakName:'Cloak',cloakDesc:'a second dash in the air',umbrellaName:'Umbrella',umbrellaDesc:'hold jump while falling to glide',
  mushName:'Red mushroom',mushDesc:'+100 mana',manaUpName:'Star pollen',manaUpDesc:'increases your mana by 25% (up to 4 times)',shotsName:'Shroom bunch',shotsDesc:'2 mushrooms a throw (8 mana), then 3 (10)',
  noMoney:'not enough spores',fullHp:'health is already full',maxHp:'can’t carry more hearts',fullMana:'mana is already full',owned:'already owned',
  shopPrompt:'E: shop',buyLabel:(n,p)=>`Buy ${n} for ${p} spores`}
};
let lang='en';
try{const v=localStorage.getItem('grib-lang');if(v&&I18N[v])lang=v}catch(e){}
function T(k){return I18N[lang][k]}
function applyLang(){
  document.documentElement.lang=lang; document.title=T('docTitle');
  document.getElementById('bj').textContent=T('tJump');
  document.getElementById('bs').textContent=T('tShoot');
  document.getElementById('bm').textContent=T('tThrow');
  document.getElementById('bd').textContent=T('tDash');
  document.getElementById('bshop').textContent=T('tShop');
}
applyLang();

